spring:
  h2.console:
    enabled: true
    path: '/console'
  main:
    banner-mode: off
  datasource:
    url: 'jdbc:h2:file:D:/develop/Programowanie/Kursy/udemy/Spring/bazaDanych/toDoApp/to-do'
  jpa:
    hibernate:
      ddl-auto: validate
